### ISSUE TITLE
Validation Fails When Posting - Error 422 Unprocessable Entity Char Limit Exceeded

### ISSUE THREAD

**Issue by Drakynn** [codl/mastodon-apod#140]
Bot is authenticating properly when first started, but fails to post content with the following error

```
[2022-12-31 20:21:30] apod: Starting ApodBot apod
[2022-12-31 20:21:30] apod.check_apod: Started
[2022-12-31 20:21:30] apod: Startup complete.
[2023-01-01 01:28:08] apod.check_apod: Exception encountered in @interval function: MastodonAPIError('Mastodon API returned error', 422, 'Unprocessable Entity', 'Validation failed: Text character limit of 500 exceeded')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ananas/ananas.py", line 377, in interval_threadproc
    f()
  File "/root/mastodon-apod-main/apod.py", line 221, in check_apod
    self.mastodon.status_post(post_text, media_ids=medias)
  File "/usr/local/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mastodon/Mastodon.py", line 102, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mastodon/Mastodon.py", line 1776, in status_post
    return self.__api_request('POST', '/api/v1/statuses', params, headers = headers, use_json = use_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mastodon/Mastodon.py", line 3425, in __api_request
    raise ex_type(
mastodon.Mastodon.MastodonAPIError: ('Mastodon API returned error', 422, 'Unprocessable Entity', 'Validation failed: Text character limit of 500 exceeded')```

**Comment by Drakynn** [comment]
It seems to be spitting the above error every 6 hours when it activates to check in and post.

**Comment by Drakynn** [comment]
Manually initializing the first post does solve the problem.  Good catch.   Thanks.
